name: gh-pages

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /injicare_event/
      # - name: Create.env
      #   shell: bash
      #   env:
      #     SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      #     SUPABASE_ANONKEY: ${{ secrets.SUPABASE_ANONKEY }}
      #   run: |
      #     touch env.json
      #     echo '{
      #       "SUPABASE_URL" : "${{ secrets.SUPABASE_URL }}",
      #       "SUPABASE_ANONKEY" : "${{ secrets.SUPABASE_ANONKEY }}"
      #     }' > env.json
